### ISSUE TITLE
Enable Host Action Commands

### ISSUE THREAD

**Issue by OddFrog** [schmttc/EasyThreeD-K7-STM32#13]
I've been running the backlash fix branch with input-shaping on Octoprint for a little over a month now and its been great but without host action commands Octoprint cant pull certain information such as feed and flow rate. It would be great to have them enabled.

**Comment by schmttc** [comment]
Great to hear the firmware is working well :)
I've updated the backlashfix branch, the single binary has Backlash Compensation + fix, Input Shaping, and Host Action Commands enabled.

**Comment by OddFrog** [comment]
Fantastic Thank you!
