### ISSUE TITLE
non-maple micro SD SPI SS don't working

### ISSUE THREAD

**Issue by kossnikita** [schmttc/EasyThreeD-K7-STM32#14]
Does this work with non maple? 

With any Marlin configuration the micro SD card does not work due to Chip Select not working. It is always at a high level, although the bootloader and maple firmware work fine.

**Comment by schmttc** [comment]
Not as far as I know, I tried to compile with non maple once but when it didn't work I just reverted to maple.
Are there any issues or features missing with the maple build?

**Comment by kossnikita** [comment]
Maple works fine so far

**Comment by schmttc** [comment]
Closing as we have the maple option
