### ISSUE TITLE
Support for K7 with bed leveling buttons

### ISSUE THREAD

**Issue by Vexisu** [schmttc/EasyThreeD-K7-STM32#16]
Hi,
as mentioned in https://github.com/schmttc/EasyThreeD-K7-STM32/issues/15, it seems like there is a newer, black and blue version of K7 printer. In terms of interaction, connections for buttons are exactly like in K9, so I've made a fork from K9's branch, but changed other parameters to mimic original K7's behaviour. Right now I don't have time to test it properly, but at first look, printer works as it should.

Fork: https://github.com/Vexisu/EasyThreeD-K7-STM32/tree/ET4000PLUS-K7-rev-B

Edit:
Found out that there is also an orange K7 with these buttons.

**Comment by schmttc** [comment]
Thanks! A bit delayed, but I've added a link to your code in the main readme to direct users.
I have a long term intention to 'unify' the firmware by making the different options a variable in configuration.h, but it's not a high priority right now.
