### ISSUE TITLE
K7 with ATmega1284

### ISSUE THREAD

**Issue by tux-friend** [schmttc/EasyThreeD-K7-STM32#3]
Hello
So I have a K7 with ET-4000 V2 board with ATmega 1284. Would this marlin version also work for the atmega?
I found out that the Board version would be Melzi for the ATmega, but do I need to change anything else?

**Comment by schmttc** [comment]
With a different board, you may also need an updated src\pins file.
You can email info@easythreed.com and ask them for a copy of the source code for your board. You can then see which board profile they use to compile, and if they have made any changes to the relevant pins file.

**Comment by tux-friend** [comment]
Got your Mod V1 ported to K7. Great and really nice work! Thanks!

**Comment by schmttc** [comment]
Glad it's all working for you! I've linked to your firmware in the README of this project in case anyone is looking for it.
